source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               version.properties,\
               plugin.properties,\
               3rdparty/antlr/antlr4-4.10.1.jar,\
               3rdparty/antlr/antlr4-runtime-4.10.1.jar
src.includes = version.properties,\
               META-INF/,\
               plugin.properties

