/*
 * MDIX - Model Driven Message Interoperability Runtime.
 * ...
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
package org.mdmi.validation;

import org.mdmi.MDMIDatatype;

/**
 * A sample validator interface for {@link org.mdmi.Field}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FieldValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateMinOccurs(int value);

	boolean validateMaxOccurs(int value);

	boolean validateDatatype(MDMIDatatype value);

	boolean validateDescription(String value);
}
